VERSION = "0.1.0"

VEBUS_SERVICE_NAME = "com.victronenergy.vebus.solis"
MPPT_SERVICE_NAME = "com.victronenergy.solarcharger.solis"

DEFAULT_CONFIG_PATH = "/data/dbus-solis/config.json"

PRODUCT_ID_VIRTUAL = 0xFFFF

DEFAULT_VEBUS_INSTANCE = 260
DEFAULT_MPPT_INSTANCE = 261

DEFAULT_MQTT_PORT = 1883
DEFAULT_MQTT_TOPIC = "solis/venus/update"
DEFAULT_MQTT_CLIENT_ID = "venus-dbus-solis"
DEFAULT_MQTT_KEEPALIVE = 30

DEFAULT_STALE_TIMEOUT_SECONDS = 10
DEFAULT_GRID_CURRENT_LIMIT_AMPS = 100.0

STATE_OFF = 0
STATE_FAULT = 2
STATE_BULK = 3
STATE_ABSORPTION = 4
STATE_FLOAT = 5
STATE_PASSTHRU = 8
STATE_INVERTING = 9
STATE_POWER_ASSIST = 10
STATE_EXTERNAL_CONTROL = 252

MODE_CHARGER_ONLY = 1
MODE_INVERTER_ONLY = 2
MODE_ON = 3
MODE_OFF = 4

ACTIVE_INPUT_GRID = 0
ACTIVE_INPUT_DISCONNECTED = 240